version: '3.3'

services:
  database:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Cardheure
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - psql-data:/var/lib/postgresql/data
      - ./docker-compose/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  psql-data:
